sudo: false

language: node_js

node_js:
    - "lts/*"

os: linux

before_install:
    - npm --version
    - node --version

install:
    - npm install

script:
    - npm run lint
    - npm test
    - npm run build
